### ISSUE TITLE
Public message to you (Game Engine Programming)

### ISSUE THREAD

**Issue by InlineEngine** [invghost/Graphite#18]
Are you looking for a C++ Game Engine/Game developer team (7 members) to gain deep knowledge? Professionals and beginners are welcome.
- The engine's PBR graphics is based on DirectX 12 with a fully flexible graph based system like UE4
- In addition we highly focus on our own Editor & GUI system's structure to make it better than public industry standards like (UE4, Unity, CryEngine, etc)
- We always use the most modern field proven paradigms created by the best developers in the world, like, multithreaded job system used in Uncharted4's engine
- Our goal is to develop an engine that is super fast and comfortable to use, We think industry standard is far behind these thinkings.	

Engine Source: https://github.com/petiaccja/Inline-Engine
If you are interested send an e - mail to: InlineEngine@gmail.com

**Comment by AraHaan** [comment]
Why Direct X 12? OpenGL is the same thing but instead of just targeting Windows the game would gain more users and ground on platforms like Linux as well. Not to mention I heard there is also an linux version of steam so you guys could benefit from it. Also with my repo you guys could specify the version of OpenGL to use as well. https://github.com/AraHaan/cppgl

**Comment by invghost** [comment]
Github issues isn't meant for advertising, i'm sure there are better communication channels for that.
